/gazebo_ros_control:   
  pid_gains:
    right_rotor_joint:
      p: 10.0
      i: 0.01 
      d: 10.0
    left_rotor_joint:
      p: 10.0
      i: 0.01 
      d: 10.0
    arm_to_left_tilt:
      p: 10.0
      i: 0.01 
      d: 10.0
    arm_to_right_tilt:
      p: 10.0
      i: 0.01 
      d: 10.0